CHARACTER_MODES = [
    "president",
    "minister",
    "leader",
    "wise_african_elder",
    "father",
    "mother",
    "podcast_host",
    "academy_teacher",
    "preacher",
    "community_chief",
    "youth_activist",
    "rapper",
    "narrator",
    "storyteller",
    "tribal_griot",
    "radio_journalist",
]
