EMOTIONAL_MODES = [
    "romantic",
    "poetic",
    "dramatic",
    "heroic",
    "sad",
    "calm",
    "passionate",
    "sarcastic",
    "humor",
    "critical",
    "aggressive",
    "soft",
    "reflective",
    "spiritual",
    "motivational",
]
